# Generated by Django 5.2.7 on 2025-10-31 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['user__first_name', 'user__last_name'], 'permissions': [('view_history', 'Can view customer history')]},
        ),
    ]
